import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect } from "react";

export const Route = createFileRoute("/blog/how-ai-changing-advertising")({
  component: BlogPost1,
});

function BlogPost1() {
  useEffect(() => {
    document.title = "How AI is Changing Advertising for Local Businesses | AdSynth Blog";
  }, []);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-100 font-sans">
      <nav className="border-b border-gray-200 dark:border-gray-800 bg-white/80 dark:bg-gray-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 text-xl font-bold tracking-tight text-gray-900 dark:text-gray-100">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-brand-500 to-purple-500 text-sm text-white font-bold">
              A
            </span>
            <span>AdSynth</span>
          </Link>
          <Link to="/blog" className="text-gray-500 hover:text-brand-500 font-medium">Back to Blog</Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 py-20">
        <div className="mb-10">
          <nav className="flex mb-8 text-sm font-medium text-gray-500 dark:text-gray-400" aria-label="Breadcrumb">
            <ol className="inline-flex items-center space-x-1 md:space-x-3">
              <li className="inline-flex items-center">
                <Link to="/" className="hover:text-brand-500 transition-colors">Home</Link>
              </li>
              <li>
                <div className="flex items-center">
                  <svg className="w-4 h-4 text-gray-400 mx-1" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clipRule="evenodd" /></svg>
                  <Link to="/blog" className="ml-1 hover:text-brand-500 transition-colors md:ml-2">Blog</Link>
                </div>
              </li>
              <li>
                <div className="flex items-center">
                  <svg className="w-4 h-4 text-gray-400 mx-1" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clipRule="evenodd" /></svg>
                  <span className="ml-1 md:ml-2 text-gray-400 dark:text-gray-500 truncate max-w-[150px]">How AI is Changing...</span>
                </div>
              </li>
            </ol>
          </nav>
          <div className="text-center">
            <div className="flex items-center justify-center gap-4 mb-6 text-sm text-gray-500 uppercase tracking-widest font-semibold">
              <span>June 30, 2026</span>
              <span className="w-1 h-1 bg-gray-300 rounded-full"></span>
              <span>Technology</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold leading-tight mb-8">
              How AI is Changing Advertising for Local Businesses
            </h1>
            <div className="aspect-video bg-gradient-to-br from-brand-500/10 to-purple-500/10 rounded-3xl flex items-center justify-center text-6xl mb-12 shadow-inner">
              🤖
            </div>
          </div>
        </div>

        <div className="prose prose-lg dark:prose-invert max-w-none">
          <p className="text-xl text-gray-600 dark:text-gray-400 mb-8 leading-relaxed">
            In the competitive world of local service businesses—whether you're a plumber in Phoenix or a dentist in Denver—getting your message in front of the right people is only half the battle. The real challenge is stopping the scroll with an ad creative that actually converts.
          </p>

          <p className="mb-6">
            Traditionally, local business owners had two choices: spend thousands on a boutique creative agency or try to DIY it with stock photos and basic templates. AI has changed the game.
          </p>

          <h2 className="text-2xl font-bold mt-10 mb-4">What are AI Ad Creatives?</h2>
          <p className="mb-6">
            AI ad creatives are marketing assets (images, headlines, and copy) generated by advanced algorithms trained on millions of successful advertising campaigns. Unlike generic templates, these are optimized for conversion from the ground up.
          </p>

          <h2 className="text-2xl font-bold mt-10 mb-4">Benefits for Local Businesses</h2>
          <ul className="list-disc pl-6 space-y-4 mb-8">
            <li><strong>Speed:</strong> Get high-quality ads in minutes, not weeks.</li>
            <li><strong>Affordability:</strong> Save thousands on monthly agency retainers.</li>
            <li><strong>Data-Driven:</strong> AI knows what works for your specific industry, from HVAC to landscaping.</li>
            <li><strong>Variety:</strong> Easily test different marketing angles to see which one resonates with your local community.</li>
          </ul>

          <p className="mb-12">
            At AdSynth, we've bridged the gap between cutting-edge AI and local business needs. Our platform delivers monthly batches of premium, platform-optimized creatives designed to drive real results.
          </p>

          <div className="bg-brand-50 dark:bg-brand-950 p-8 rounded-2xl border border-brand-100 dark:border-brand-900">
            <h3 className="text-xl font-bold mb-4">Ready to upgrade your marketing?</h3>
            <p className="mb-6">Join hundreds of local businesses using AdSynth to grow their leads while lowering their costs.</p>
            <Link to="/#pricing" className="inline-block bg-brand-500 hover:bg-brand-600 text-white px-6 py-3 rounded-xl font-bold transition-all">
              Get Started with AdSynth
            </Link>
          </div>
        </div>
      </main>

      <footer className="py-20 border-t border-gray-200 dark:border-gray-800 text-center text-gray-500 text-sm">
        <p>&copy; {new Date().getFullYear()} AdSynth. All rights reserved.</p>
      </footer>
    </div>
  );
}
